### ISSUE TITLE
Maven reactor builds are broken with the `--all-projects` flag

### ISSUE THREAD

**Issue by jebeaudet** [snyk/snyk-mvn-plugin#124]
- `node -v`: v14.17.1
- `npm -v`: 8.3.0
- `snyk -v`: 1.693
- Command run: `snyk test --all-projects`

### Expected behaviour
Properly analyze all my dependencies for my reactor project.

### Actual behaviour
The `all-projects` flag treats every module as a separate project which is wrong in the context of a reactor build. Modules are built together and in a specific order (as shown in the `Reactor Build Order` output of a simple `mvn compile`). Treating them separately just doesn't work for unpublished versions (which is often the case when wanting to release a new version and run snyk on the exact commit hash about to be released).

Moreover, this could lead to a false analysis by not taking the proper version into account. For example, if you have module-a pulling on module-b with version ${project.version}, maven will look in the <repositories> for a hit on module-b at version ${project.version} which could lead to incorrect dependencies in the case of SNAPSHOT versions or non-immutable versions (not possible on maven central but possible on private maven repositories).

### Steps to reproduce
1. checkout https://github.com/jebeaudet/snyk-mvn-plugin/tree/complex-agg-project
2. `npm run test` (I've added a simple failing test)

Or manually with the CLI : 
1. checkout https://github.com/jebeaudet/snyk-mvn-plugin/tree/complex-agg-project
2. `cd snyk-mvn-plugin/tests/fixtures/complex-aggregate-project`
3. `snyk test --all-projects`

---

**Comment by jebeaudet** [comment]
Related PR : #114

**Comment by jebeaudet** [comment]
I don't believe anything has changed with regard to this issue in Maven 4.

You have some more info in this [mailing list thread](https://www.mail-archive.com/users@maven.apache.org/msg104341.html) or this [SO thread](https://stackoverflow.com/questions/1677473/maven-doesnt-recognize-sibling-modules-when-running-mvn-dependencytree). 

A `mvn install` invocation might work in most cases but to me it's still wrong to treat modules of a reactor build independently like the `--all-projects` does, it just does not make sense in the context of reactor builds. Moreover, I see these 2 additional issues :
1. `mvn install` will run tests by default, along with all the other plugins defined in the install phase and lower. Tests could be skipped with `-DskipTests` but other plugins might fail for any reason (ie. a VCS plugin could assume there's a `.git` folder when there might be none)
2. it will increase snyk run time _a lot_ by doing that since all the dependencies will be downloaded locally in the install process which is just wasteful in the end for the purpose of analyzing dependencies

To me, the proper solution for this is to detect reactor builds projects and treat them accordingly. So, with the `--all-projects` flag that recurse into sub directories, it should traverse the filesystem, get all the `pom.xml` files, find which one are reactor builds and which one are not. Then, run the `mvn dependency:tree` command on parent pom (the dependency plugin works properly for all the modules of a reactor build when invoked at the parent pom) and standalone modules but not on modules that are part of a reactor build. This way, I believe you get the intended behavior of the all projects flag along with proper dependency resolution of reactor builds _without_ installing anything in the local repository, avoiding the caveats I've mentioned above.

**Comment by gitphill** [comment]
We're working on a new Reactor test something like `snyk test --use-mvn-reactor` (name not confirmed) that will perform `mvn dependency:tree` in the root without `--non-recursive` to allow the reactor to do the heavy lifting. We can then produce multiple graphs on that output.

We have multiple scan results from one command in the snyk-gradle-plugin already so shouldn't require too much effort in the Snyk CLI. I'll let you know when it's available.

**Comment by gitphill** [comment]
Hi 👋  @jebeaudet 

Sorry for the delay, we have now released a version of the Snyk CLI that should support this issue.
Get the latest CLI `npm i -g snyk` it needs to be `1.987.0` or above (`snyk -v` to see the version you have).

To use the new functionality add `--maven-aggregate-project` to your snyk CLI arguments and run from the root pom.xml file's directory. So for example:

`snyk test --maven-aggregate-project ./tests/fixtures/complex-aggregate-project`

We now run `test-compile mvn dependency:tree -DoutputType=dot` without `--non-recursive` and parse all of the Maven reactor digraph output into Snyk dep-graphs.

Please let us know if this helps

**Comment by jebeaudet** [comment]
I've since left the company that was using snyk but maybe @fredboutin could test it out real quick.

**Comment by fredboutin** [comment]
Not me, but someone is going to have a look at it and report back. @JPLachance maybe
