### ISSUE TITLE
Update travis tests to use stages +  add support for java 10 & 11

### ISSUE THREAD

**Issue by lili2311** [snyk/snyk-mvn-plugin#31]
### Expected behaviour
The code is tested on java 10 & java 11 too, to bring support up to date

### Actual behaviour
Only 8 & 9 currently tested

### Example
Here is an example travis config that would be ideal: https://github.com/snyk/snyk-gradle-plugin/pull/84/files

This blocks: https://github.com/snyk/snyk/pull/710

**Comment by sfat** [comment]
@lili2311 this can be closed, right?
