### ISSUE TITLE
Run compile phase systematically with dependency:tree

### ISSUE THREAD

**Issue by jebeaudet** [snyk/snyk-mvn-plugin#38]
Hi

You should add the `compile` phase along with the `dependency:tree` goal in order to support multi module project that have not all their artifacts published. This [SO thread](https://stackoverflow.com/questions/1677473/maven-doesnt-recognize-sibling-modules-when-running-mvn-dependencytree) says it nicely, there is no other workaround for now.

For some context, we use your tool in our Snyk organization to run against a specific project _before_ it's deployed to production. After the production deployment is successful, only then the artifacts of the project are published on our internal maven repository.

**Comment by felixbarny** [comment]
We're also running into this problem. The fix should be as simple as adding `'compile'` as the first element in the list:

https://github.com/snyk/snyk-mvn-plugin/blob/f06e71f56a152c2dc640d0e9918274fa56f05d4e/lib/index.ts#L158

All multi-module maven projects are affected by this.

**Comment by jebeaudet** [comment]
I'd even go as run `test-compile` instead as it includes `compile`. If you have any module pulling on another one in the test scope you'll need this.

We solved it by passing the argument ourselves on the command line when running our snyk scan.

**Comment by felixbarny** [comment]
> We solved it by passing the argument ourselves on the command line when running our snyk scan.

Nice, how do you do that?

**Comment by jebeaudet** [comment]
We use docker : 
```
docker run -e "ENV_FLAGS=test-compile" -e "SNYK_TOKEN=XXX" -v /project-dir:/project snyk/snyk-cli:1.297.2.maven-3.6.3_java11 test```
```
In the CLI, you can do (the space after `--` is important!) : 
```
snyk test -- test-compile
```

**Comment by seanf** [comment]
I can't get the `test-compile` workaround to work. Maybe this has changed in the last two years, but it seems that Snyk invokes `mvn dependency:tree` separately for each module, eg `mvn dependency:tree -DoutputType=dot --file="module/pom.xml"`. Adding `test-compile` to the end of that doesn't help, because the other modules aren't in Maven's reactor.

**Comment by seanf** [comment]
When `mvn dependency:tree` fails, an error message like "1/6 potential projects failed to get dependencies" is logged, but what's concerning is that `snyk-cli` returns success (0) anyway.

**Comment by jebeaudet** [comment]
@seanf are you running with the `--all-projects` flag? What's your exact command line and project structure?

**Comment by seanf** [comment]
> @seanf are you running with the `--all-projects` flag? What's your exact command line and project structure?

I was, yes. Without `--all-projects`, there's no error, but Snyk only reports on the top level pom project, with a suggestion to use `--all-projects`.

```
snyk test --fail-on=all --severity-threshold=high --all-projects -- test-compile
```

The project structure:
```
parent-pom
├──a
├──b
├──c
└── application (depends on a, b and c)
```

It is the `application` module which trips up `mvn dependency:tree`. 

In this project, `mvn dependency:tree` only works if run at the top level, in which case it generates a tree for each module in turn (even without `test-compile`). If it is run like this: `./mvnw dependency:tree -DoutputType=dot --file="application/pom.xml" test-compile` (as Snyk does), it can't resolve the POMs and jars for `a`, `b` and `c` (unless they have previously been installed by `mvn install`).

**Comment by jebeaudet** [comment]
Yea ok then you have the exact same problem as us. We unfortunately gave up on the `--all-projects` flag for now, it's clearly not done for unpublished multi-modules reactor projects as you can see. You can try installing then running snyk but it's a real PITA and should not be necessary.

**Comment by jebeaudet** [comment]
@seanf your issue is caused by https://github.com/snyk/snyk-mvn-plugin/pull/114.

**Comment by gitphill** [comment]
Hi 👋 @jebeaudet @seanf @felixbarny 

Sorry for the delay, we have now released a version of the Snyk CLI that should support this issue.
Get the latest CLI npm i -g snyk it needs to be 1.987.0 or above (snyk -v to see the version you have).

To use the new functionality add --maven-aggregate-project to your snyk CLI arguments and run from the root pom.xml file's directory. So for example:

snyk test --maven-aggregate-project ./tests/fixtures/complex-aggregate-project

We now run test-compile mvn dependency:tree -DoutputType=dot without --non-recursive and parse all of the Maven reactor digraph output into Snyk dep-graphs.

Please let us know if this helps
